name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x App/gradlew

    - name: Gradle Build
      run: |
        cd App  
        ./gradlew build


    - name: Run Unit Tests
      run: |
        cd App
        ./gradlew test

    - name: Run Android Tests
      run: |
        cd App
        echo no | android create avd --force -n test -t android-28 --abi armeabi-v7a
        emulator -avd test -no-audio -no-window & android-wait-for-emulator
        adb shell input keyevent 82 &
        ./gradlew connectedAndroidTest


      
